openapi: 3.0.0
info:
  title: Company Microservice API
  description: This API manages the companies in SkillVerse
  version: 1.0.0

paths:
  /companies:
    get:
      summary: List all companies
      operationId: getAllCompanies
      parameters:
        - name: only
          in: query
          description: Array of company IDs to fetch a subset of companies
          required: false
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
        - name: full
          in: query
          description: Determines if the nested data will be returned
          required: false
          explode: true
          schema:
            type: boolean
      responses:
        "200":
          description: A list of companies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Company"

    post:
      summary: Create a new company
      operationId: createCompany
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Company"
      responses:
        "201":
          description: Company created
        "400":
          description: Invalid request data

  /companies/{companyId}:
    get:
      summary: Get a company by ID
      operationId: getCompanyById
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
        - name: full
          in: query
          description: Determines if the nested data will be returned
          required: false
          explode: true
          schema:
            type: boolean
      responses:
        "200":
          description: Company details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Company"
        "404":
          description: Company not found

    put:
      summary: Update a company
      operationId: updateCompany
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Company"
      responses:
        "200":
          description: Company updated
        "404":
          description: Company not found
        "400":
          description: Invalid request data

    delete:
      summary: Delete a company
      operationId: deleteCompany
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Company deleted
        "404":
          description: Company not found

components:
  schemas:
    Company:
      type: object
      required:
        - name
        - industry
      properties:
        id:
          type: string
          description: Unique identifier for the company
        name:
          type: string
          description: Name of the company
        industry:
          type: string
          description: Industry in which the company operates
        metadata:
          type: object
          additionalProperties: true
          description: Additional metadata related to the company
