openapi: 3.0.0
info:
  title: Authentication & Authorization API
  version: '1.0'

paths:
  /login:
    post:
      summary: User Login
      description: Endpoint for user authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  description: User's password
      responses:
        '200':
          description: Successful login
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /user:
    get:
      summary: Get User Information
      description: Endpoint for retrieving user details
      parameters:
        - name: email
          in: query
          description: User's email address
          required: true
          schema:
            type: string
            format: email
      responses:
        '200':
          description: Successful retrieval of user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    format: email
                    description: User's email address
                  password:
                    type: string
                    description: User's password (Note: For demonstration purposes only; don't expose passwords in a real API)
                  company:
                    type: string
                    description: User's company
                  userRole:
                    type: string
                    description: User's role (employee or employer)
