openapi: 3.0.0
info:
  title: Tags Microservice API
  description: This API allows for managing tags with categories and supports fetching subsets of tags.
  version: 1.0.0
paths:
  /tag:
    get:
      summary: List all tags or a subset based on tag IDs
      operationId: listTags
      parameters:
        - name: only
          in: query
          description: Array of tag IDs to fetch a subset of tags
          required: false
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: A list of tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tag"

    post:
      summary: Create a new tag
      operationId: createTag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Tag"
      responses:
        "201":
          description: Tag created

  /tag/{tagId}:
    get:
      summary: Get a tag by ID
      operationId: getTagById
      parameters:
        - name: tagId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Tag details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tag"
        "404":
          description: Tag not found

    put:
      summary: Update a tag
      operationId: updateTag
      parameters:
        - name: tagId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Tag"
      responses:
        "200":
          description: Tag updated
        "404":
          description: Tag not found

    delete:
      summary: Delete a tag
      operationId: deleteTag
      parameters:
        - name: tagId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Tag deleted
        "404":
          description: Tag not found

components:
  schemas:
    Tag:
      type: object
      required:
        - name
        - category
      properties:
        id:
          type: integer
          description: Unique identifier for the tag
        name:
          type: string
          description: Name of the tag
        category:
          type: string
          description: Category of the tag
